"""empty message

Revision ID: 872ff662cb12
Revises: d295996ddd25
Create Date: 2024-07-24 18:25:21.331164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872ff662cb12'
down_revision = 'd295996ddd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_planets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fav_people', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['fav_planets'], ['id'])
        batch_op.create_foreign_key(None, 'person', ['fav_people'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fav_people')
        batch_op.drop_column('fav_planets')

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fav_planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fav_people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fav_people'], ['person.id'], name='favorites_fav_people_fkey'),
    sa.ForeignKeyConstraint(['fav_planets'], ['planet.id'], name='favorites_fav_planets_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
